  #第三方登入
  production:
  GOOGLE_CLIENT_ID: '294652703424-dlgik1qvrhp30runo4dr9v797vuftmll.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET: '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'
  FACEBOOK_CLIENT_ID: '2935989426700919'
  FACEBOOK_CLIENT_SECRET: '3743d1aa3e08569351a3cd7acaeaef76'
  GITHUB_CLIENT_ID: '718504a7099760642747'
  GITHUB_CLIENT_SECRET: 'f4235bb536bedc7c7b5d8bbe32e4660a607d189d'
  TWITTER_CLIENT_ID: 'LVUtY2l5X09Cc3hFR0xVakd6dHI6MTpjaQ'
  TWITTER_CLIENT_SECRET: 'SW_I0gpN51JeHuPMyNUVK-yp1Kia4FRIeXOMJ1NJ0OoRT_5I-9'
  development:
  GOOGLE_CLIENT_ID: '294652703424-dlgik1qvrhp30runo4dr9v797vuftmll.apps.googleusercontent.com'
  GOOGLE_CLIENT_SECRET: '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'
  FACEBOOK_CLIENT_ID: '2935989426700919'
  FACEBOOK_CLIENT_SECRET: '3743d1aa3e08569351a3cd7acaeaef76'
  GITHUB_CLIENT_ID: '718504a7099760642747'
  GITHUB_CLIENT_SECRET: 'f4235bb536bedc7c7b5d8bbe32e4660a607d189d'
  TWITTER_CLIENT_ID: 'LVUtY2l5X09Cc3hFR0xVakd6dHI6MTpjaQ'
  TWITTER_CLIENT_SECRET: 'SW_I0gpN51JeHuPMyNUVK-yp1Kia4FRIeXOMJ1NJ0OoRT_5I-9'
